version: 2

# Set defaults to reuse
defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:8.9.1

jobs:
  test:
    <<: *defaults
    steps:
      - checkout

      - restore_cache:
          keys:
            - v2-dependencies-
            # fallback to using the latest cache if no exact match is found
            - v2-dependencies-

      - run: npm install
      - run:
          name: Run tests
          command: npm test
      - run:
          name: Send to Coveralls
          command: cat coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-

      - persist_to_workspace:
          root: ~/repo
          paths: .
  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Put To Pages
          command: npm run docs:publish

workflows:
  version: 2
  test-deploy:
    jobs:
      - test:
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
      - deploy:
          requires:
            - test
          filters:
            tags:
              only: /^v[0-9]+\.[0-9]+\.[0-9]+/
            branches:
              ignore: /.*/
