'use strict';

const _ = require('lodash'),
  clayUtils = require('clayutils'),
  files = require('nymag-fs'),
  path = require('path'),
  traverse = require('traverse');

/**
 * Looks for CSS files associated with a component's variation
 *
 * @param {String} styleguide - name of the styleguide that is set in the sites config
 * @returns {string[]} variations
 */
function findVariationFiles(styleguide) {
  const stylePath = `styleguides/${styleguide}/components`,
    stylesheets = files.getFiles(stylePath),
    variations = _.filter(stylesheets, function (file) {
      // checks for underscores which denotes variations and make sure it's a
      // css file
      return file.includes('_') && file.includes('.css');
    });

  return variations;
}

/**
* Grabs variations of all components and returns an object organized by
* components and their variations
*
* @param {String} styleguide - name of the styleguide that is set in the sites' config
* @returns {Object} componentVariations - an object that is organized by
* component and its variations
*/
function getVariations(styleguide) {
  const foundVariations = styleguide ? findVariationFiles(styleguide) : [],
    componentVariations = {};

  if (foundVariations.length) {
    _.forEach(foundVariations, function (variant) {
      let component = variant.split('_')[0],
        variantName = path.basename(variant, '.css');

      (componentVariations[component] || (componentVariations[component] = [])).push(variantName);
    });
  }
  return componentVariations;
}

/**
* Goes through page data and sets a default for components that
* have variations but don't have any set. Note: this mutates the array!
*
* @param {object} pageData
* @param {object} variations - all components with variations, usually generated by getVariations
*/
function setDefaultVariations(pageData, variations) {

  traverse(pageData).forEach(function (val) {
    const componentName = _.isObject(val) && val._ref ? clayUtils.getComponentName(val._ref) : undefined;

    if (componentName && variations[componentName]) {
      if (!val.componentVariation) {
        _.set(val, 'componentVariation', componentName);
      }
    }
  });
}

exports.getVariations = _.memoize(getVariations);
exports.setDefaultVariations = _.memoize(setDefaultVariations);
