name: Deploy to GitHub Pages

on:
  push:
    branches: [master]

jobs:
  deploy-docs:
    name: Deploy docs
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '16'

      - name: Install website dependencies
        run: npm install
        working-directory: website

      - name: Update Docusaurus version
        uses: clay/docusaurus-github-action@f3ea5271a51c1f06e456d55e490993985210c02b
        with:
          args: version

      - name: Build and publish to gh-pages
        uses: clay/docusaurus-github-action@f3ea5271a51c1f06e456d55e490993985210c02b
        env:
          DEPLOY_SSH_KEY: ${{ secrets.DEPLOY_SSH_KEY }}
        with:
          args: deploy
